#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t SuperTeam"

$L "Welcome to Android `getprop ro.build.version.release` / `getprop ro.osr.version`";

$L "  ______                       ________      _______             ";            
$L " /  ___/___  _________________/___  __/_____/  ____ \__________  "; 
$L " \___ \ / / / / __ \/ _ \ / ___/ / /   / _ \/ / __ \/_ \__ \__ \ ";
$L " ___/ // /_/ / /_/ /  __// /    / /   /  __/ / /_/ / / / / / / / ";
$L "/____/ \____/ ____/\___//_/    /_/    \___/\ \__,_/ /_/ /_/ /_/  ";
$L "           /_/                              \____/               ";
$L "                                                                 ";
